# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:U4O184KX9Vm4Q1QHxOjV5IF3Wps9e19DFtNnrSYcpErZE7+eOav+2/VLA9cTCgcs8Qk5QoeFw01J+une1GCi97AqMcyh7OB6g+zinlZYVoyGXTpOFuWpwgNix0LTjRH7JvJCdZn6y4s1ZBf0F1dwKrgg4ZtPBa7cdApQjHHlbnoc9dlULWYLidDe8xp4Oa09TOMVpsjdQPVrqRq7iuOY3oyrjfyntcaPSiTYzIQooAne+2ppeg==,iv:5jIJMVOT+7retdCuwWm8NfNqt5S3t6IChs/87p7kzhs=,tag:6/v8Fj8dC0yivc1o0iJQkw==,type:str]
sops:
  age:
    - recipient: age1y867m67ad9y7ces58pfkayxw8qce9ls6sk4z33hx6yvztjryrafs4n42ru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvU0VtRUJhL2pyN2Vic2pF
        c1B1N1ZCZXhxVUxuOXFPZ09rNWJaaW43ckNvCkg3WjlSVGNSaEYzaS9XbnR2amtn
        S0RDTHBLK2xOTzFsbUlZQStGYnAvZm8KLS0tIDUwVVN1MDJqTUZkZFBzNXRkczRF
        OXRZQys3MlZITFMvK3IrTGxJMHRYZncK5Vr3PRWL13qaoVdbIBfDUiMeHZZqqtP0
        SMKN380FUH3T4CEe2dXCckmPHeI59t9d6Td1z0mOICoaGDG+GsdvEQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-05T21:11:46Z"
  mac: ENC[AES256_GCM,data:j6NsCXmfN9lCH4rUcWpWFa6OAXqLNHaqVu9UrhgswLOuiqKaO67ekPCWovXBf/UEqbfflorvM1g+Vi1mS+6ti1K8Cc3jRYwVkun4604PB55N/7BSI8JtIuFdaTewXeMpK/6/kfDMUFbY0e1MvIRFg70hCuRlX5Odmpie7SH/8xE=,iv:mdpVmAwEUj7NO7WNrR+WyCAUfbVbmLUzAqm7DgYA5Ng=,tag:ptZ1MIaplKwQoXfHxOPdDA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
