# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:n6AMc2N5SQaoNiq6qWokzgPVI+wOHw/qEi9mFmOxnJ3JDQyT0UqdvjsopNzOxeLnq3hWY8vQt7qyz5c54H2pr9ULarKc4IszbA7RfwUy9XKB03/JtqfAlybah9VO4sDrCzgkDWFTUvRXmrTf1NcKnCpkc4g53ABcUC+25FaTJ7Yt2GlAqCtGa1QT/nll0kfIVUsjiQS1D8qCCXwrXU4Rhj/uYxOvCTJOJILpQBZRou4fA+0uPw==,iv:8L5eoKdwGr9PdwDKbDbOi2TDjQMn+FnAhlX3NIXmoL0=,tag:SKqASU1sybY7aY9NlZuewQ==,type:str]
sops:
  age:
    - recipient: age1y867m67ad9y7ces58pfkayxw8qce9ls6sk4z33hx6yvztjryrafs4n42ru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRStLRUVROTJnSWVlOFRC
        SzkzdXlKQ1V2dkdkYklST1kzenRjdllMQWdFCi9pdFVmQkU3bXlWdTByOTNWUElT
        WVZ0TlJvVWFnS2Y2WmIxOXVxZkVRdTgKLS0tIFFBMFRDT1hrQjVaUWoyUFJSYUFt
        WmYra0VHQ0JmMnBUc2VodXh6dE82UmcKOAeCim2PbuWYVNfzFYccXvebgDVSNqib
        8OZrhOhjZw6U0/s//LfhI/ZEp6LAlPelb5qZGWuinaAICiTek6uY6Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-06T19:57:40Z"
  mac: ENC[AES256_GCM,data:9CBbjMCbSlhZjKKItTaclnF3N1/07Su72mCf1ifN38SMUr8H42cFwj66pQCtOYZuRt/c5pqvAy0SyDSN6j0xCbzUnD5n1fjbxYrrCBoDh/uZ3nlx8yAoI+21l2RUgdwBE4OAoNC+8qZ4sqP4Zzpc28KSZVQGzJxVQlEPI+nhh8k=,iv:DpyaoNurLgiGf4ziM1O2rl9OPQ7we8vwYLB/lCGAUoA=,tag:tgffrIYEC/KQUhYFZvpsvw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
