---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1x4aarl9ggry79j5n8uffmgnje7gnpjrcdz0aqp0kxlaaz5e42stsp0qj6w"
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1x4aarl9ggry79j5n8uffmgnje7gnpjrcdz0aqp0kxlaaz5e42stsp0qj6w"
  # https://github.com/ansible-collections/community.sops/issues/153
  - path_regex: /dev/stdin
    key_groups:
      - age:
          - "age1x4aarl9ggry79j5n8uffmgnje7gnpjrcdz0aqp0kxlaaz5e42stsp0qj6w"
