# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:XjOFBRKHhdfVqYHlnIJn3pCoZkKtpefz1pKfwccbGS7oJpEieN4qEg==,iv:ZbU4eiE6iwSxZqbf4X2RLGZXLhn1SPYp+UTwFHgMKXk=,tag:6ir3XwcN/HypZXbgNkOCRA==,type:str]
sops:
  age:
    - recipient: age1y867m67ad9y7ces58pfkayxw8qce9ls6sk4z33hx6yvztjryrafs4n42ru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0akw4dktHaFJCa2VlcmFN
        MVcvbDFiWG4yTyt0bHU2T2VNTGFQdmxPc0ZJCm5hZzBGVnBGNXJUWnZ4VC85dE9D
        dnJ6QmQ0OGU4Z253SS9PcEpuaVZNYmcKLS0tIGdVWXJDdFl0c1ZkT3BtenFkMS9T
        WHlzWktGcWpBUm5uWFZIVitOSnNna2sKuxryP9DDdakL59L3sf3mdrcme+OdX4Mi
        h5fmGtlpaJvmMayxlFU6rLYU0nVS4BFhKWM7PvqJbJFAeXoekVZ/Jg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-05T21:11:46Z"
  mac: ENC[AES256_GCM,data:1HPpsBDWsMU91PWmh2XWoA4+TGptGPN5pbQaktE/LgGNUNJLSyc/xkl9hUHJF0X5vQZLRjBZwO/wn+WXoudbHQYQfAc/Mz4sX2hA97UrovTn1s0BHqq2KxLvCNTwKGezkHRoUoCY3L3F75vSTIt/xDeTgaxcaRbrW7ll4aQZGeM=,iv:DYRCcTpCYc2TcX2uCjjNIbScWDy6yDTQginWZ48SGr0=,tag:p+CQKpx07hcvVsxT69E5+A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
