# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:/fEaiY9IMoSqzUf042Pct6pmOKeHJMux2a7huNF0dq35b4nFmQjoKg==,iv:1KxQSRgKnc9UaTyVmz6yiCH1wMoHrLiHTtt1Xfw9uaY=,tag:B2I8SCIIx42qoGhafo0laA==,type:str]
sops:
  age:
    - recipient: age1y867m67ad9y7ces58pfkayxw8qce9ls6sk4z33hx6yvztjryrafs4n42ru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdWtZeG16Y085amJkbEcw
        RWpOcGs3NXZyVy9Sb1JlTUhmVEJXaUJOZFhjClk3NDJvYWVvMmtRZ1NRdkNhM1g3
        V0g3WVIzL3VuOUZleDJNSW4xVnkrTDQKLS0tIGUxQXVyaWcvTm1uWnBBOTUzNThX
        RGtKMk1DTWp5amwvaFR6Z1RTY2QwaFkKrxFyeXZ9tv4Ai4FADi3nxCgEuR4agdtA
        33bpCh3Tw+afxLbgsJhA82QgOcVMOiQBkJ9zSJX1aLLo3Jo2cmg/dQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-01T23:53:35Z"
  mac: ENC[AES256_GCM,data:5gargvqWVOO0ZCE6UP3NZudgJ1Q3RAC+RUaYSD/QWYIm/sRF1Ql6kmXYOaZR7NvZht7mafBtx//g/DIzWN8RHmqx+LqFLEN4L8wcxPZr39A0jQdAq7ZXDsug+oYZ1MpnzGcMyLlc7dWCQayPgwnWCClPseRn6KlakbCsIGqBikg=,iv:eQIBABZ+oiTsVMiOO0ze6NIm/9lYWtVc0nfW0gL8SxA=,tag:9Sh/7sFth73HGeUwqKC4HQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
