ansible_become_pass: ENC[AES256_GCM,data:oHQU1T1Jock7,iv:fK8vRhM0ajeXH/7e//pjmqCe8rWYS/3+SwQwsKyUBKg=,tag:rWPIR8K8CrIaRVTPIWM9qw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x4aarl9ggry79j5n8uffmgnje7gnpjrcdz0aqp0kxlaaz5e42stsp0qj6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0eHQzcE5vQUx4UEVGWnNw
            QkpCK0ZwazFZTFROYkt5eUlua3VsZTJMQm1BClNNMGFrTzBKN1huL3hCSks2OFFq
            dFRnaFNvSHgyUlVTQVk4TXpWNzlhMGMKLS0tIEd0YjFPOFBtbzZhdnFyMzVVendv
            UUZyVnJnRzhoS0puZkhJOGVSMDdVcjQK1fzE6LH761JB9tCVaUaMI5B1Ffd60t66
            muBP6staFgr0ghTJvKJ2bY9gL2+AUe5tgiBP+4Ny0zHGndTCzlaIoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-10T04:59:30Z"
    mac: ENC[AES256_GCM,data:rsPPBtmdH8QAf8hrAY3wVRnUhTh7iT1dr/pYQv5j+s36TMT28lAzIGzoM1Vx/ngDeBio0zYO4pXXaM9lY92rocTUwtvgwknSSwQqdzgaTIcsPNdJH4wFrIwrEOQhEdmfhxKWszc/UoT5gj/m6Q8twsWWHNf3T2HytuIkREvvALk=,iv:jglj9Ocra+CaO8JAoPX30t9zGEEXA7g+RwII+D811hU=,tag:qCnIdzxmUMD45bdzcWKR3w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
