ansible_become_pass: ENC[AES256_GCM,data:UwPajbzt1Rxu,iv:ATLvNrrcHSzdMbuYefOAYPibYmB99xTp/id44FPJUHM=,tag:knNEkPaRfd3I+Lz8s3wSAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x4aarl9ggry79j5n8uffmgnje7gnpjrcdz0aqp0kxlaaz5e42stsp0qj6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZlA4WVVPNUN2NEVUZ3Nv
            TENCN1ZqK1J4eFRsdk84cXlGODBrNHo3Q0VBCmJISjBORFdUYlh5SUY1YThXdWpm
            eG9DTlZMdWlLUnE1TjdBemNoRS8yUU0KLS0tIGlJMWZwc1VFQ3VBOWcyeWcvb3Zy
            c0VyOHRQYUJ5L2k1RTdXMjZCWDQ1TWcKB9PzhXRexAby3zntRVDR85xYNNbnrgGN
            shvcS2m80j0SkW8wI2rSsidbKopPKt5zncJLmMjyZspbYgAXAkNN9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-10T05:02:08Z"
    mac: ENC[AES256_GCM,data:VLumOwaATM5IdffqxJE0o73DbPEilzF3rngeYkcA067zX0JrDFzCdAXdLuHTtGCqQN7XxBhkFbsIY/iGbOPQ86Z/vxBN0vNzGRhxNdBQ/znsz8wwcAyXLDfzb5lJcibMN2u8SPZOx92ePLIkY7EiIrr8kHCkRk5/VtlhstFcKYE=,iv:yPot/WKwgwUWc2TWXvApdnECZgarlylHO7u8iiv3mFE=,tag:QG+YRdJY8eC3RF6XF0HHsA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
