ansible_become_pass: ENC[AES256_GCM,data:pb8mfKF4P3J1,iv:p9LMVNDrJX+lHKIanrHKLzTR0u55napa6NAV6lzAXYo=,tag:bTOSKqC/jOMFRicd2e1mvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x4aarl9ggry79j5n8uffmgnje7gnpjrcdz0aqp0kxlaaz5e42stsp0qj6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cEo2c1Nya1F2SlB5SHk2
            cmJ3ZGZENGQzRnE5WjJnNkdYd1FBUWw0WFJRCnc1NHRweXA4Ky9ZSGcybGZXc3Ny
            Z1Y4S0xGRlI1RTBvYXd4L24vSy9TVWcKLS0tIGw4eVl3TVN6aTdnTFNKeVBKcDEv
            ZHF2S1pVTEtNVEJ3U3U1c2pjcXpadXMKPSif1g4WkTVrbYJ7jsVHHE/Qy5VNSsmh
            4hYmA7bVOhZysjhBJtN3MuvH6k8CfVN7z27EGIN6Bvd0N9iF8/yk+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-09T05:13:59Z"
    mac: ENC[AES256_GCM,data:JFVr3c02UnUNX464nr3uwDo9VySTwWQKXjfm95fRI669VtzX2TB0xetrToZC7u83JxHCzhpCfOKvrxB6FgcMVWbtTM+e1aM4PYttvaZ1PDjC1VihXoUXKJOKo1PB7ezrSpyHLupZlQu3tnjI6dwV2zpnaK3NVHaOxVBIqu1WhYc=,iv:TueiPwrgcDab9AdI+Ml5oIrjLgg2aashGG3+sO3MdJk=,tag:wKH13wK+e5NJ9taDuF4Dxg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
