ansible_become_pass: ENC[AES256_GCM,data:DyoBOHEfh4sO,iv:xC4fvr1HwW1FBLnLApP49EqQPsyV10X/Sn3BzioMTys=,tag:bZQDB4rGL/B+6NA4oLAVqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x4aarl9ggry79j5n8uffmgnje7gnpjrcdz0aqp0kxlaaz5e42stsp0qj6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUFl3M2daRnVtWTJGcGhx
            K2dGQy96cFp6Vjhhd1Z6WlBSQW1QYytmMUdrCnQvckVmT2JtRmp4R0txc0tZSk9J
            TDNOZFBCaDNkcURicnFtL3VVd3JqRDgKLS0tIE1qOVJJdWZSWDdsWEdjalAxcWtF
            ZTE2WXdFYVlrTi9uY05qY0xNbXZhSU0Ki3P4A3nl9GfABK+PZLXyu88vSOteQuKo
            7mfGgFjgBqML6Z7cQ47OxN7AT5cr6gNxzcjnoLr1i+1VW0MMyc9gJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-10T04:59:30Z"
    mac: ENC[AES256_GCM,data:YNUXqtEMHidDwfbiWbbqfYO8rpfveC7bDzQedwpGVxupYoihIRNaQ0h5QImCbBnWlm4DhWEOCRksDgtvHFklWGwWiesigPpq2Ejo0WcfunZdflksSXd2peT7adpyEJ29Tmb3p5hlj95gz9IuWlDcZlOUQ7T66yb7gpf9a5/Mio0=,iv:ktkFPvaCBvxwhzq7eT9VnpD06cBdbJJTv1q/Ed/n96c=,tag:NabiwNe61iKFit0kKKczxw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
