ansible_become_pass: ENC[AES256_GCM,data:lQjUUMVw/rai,iv:DXjk2dtglt/t9nHdVcV6UxxYzigGS8Wqrkm5M3EE+6I=,tag:S0VkDZCUuprEAxbEa738hA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x4aarl9ggry79j5n8uffmgnje7gnpjrcdz0aqp0kxlaaz5e42stsp0qj6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkellyTzF2RGYyU2psYlhH
            Q1hkN1NvTUVJL1RSR1gvTlVsdXZmeklsS1ZRCko1ZVM2bGIrSUltUURtZFRYU21Q
            Y1JOT2tDVFI3WlA4T0lMbmgwZXJYZ3cKLS0tIHJGdDZIZkx0a0hSdVcrM0RseFFt
            TnZtMjJQck9DSDhsYWhIS05XcEptQncKocx+pGJvBXmAIbCN2ioTOl2T/6861kCE
            sCcXHQu+7iv6cu04+vllNVPQF8nzGPWmV6UP5PX/5r5n6mnNSI/mcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-09T04:56:42Z"
    mac: ENC[AES256_GCM,data:6msU2/TmkX25S4xzKamRvLCxvC1FJZ2EIY+F2El7FSrMS8kssp6sQ49S/L6pE9xVHrVnlTRoFrDIrTMDsm1+efkjYW5HllE36M1dSJJnOAUNQMgAVlwOkwK+fNdKpiIXdi7mddVY3l0H71SmbgZ8naeurLi8GM8COFFMHTuoLY0=,iv:MJWnbAPzxkM2C+uuSnL8XaO91f5fwESKT7oqNFdDagk=,tag:N75CJyO41wMODo+Uzznocw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
