ansible_become_pass: ENC[AES256_GCM,data:2dG1Un5VktsB,iv:KLPff5RhjQ/O4MGLgE5ggYxA7Dk/iXs/XnS5euFDGv4=,tag:Wu/RRVVqKFZC+93C5ewxNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x4aarl9ggry79j5n8uffmgnje7gnpjrcdz0aqp0kxlaaz5e42stsp0qj6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2a1lZQ21ZbUFnQWRPc05U
            SWd1QUg2R1d2ckRhY2NRWWlOdHBsU2lKS3dzCi81NDhCaWo4OERWWDgyUjZXVmtl
            UUtaNkxiVHdZYzVMNXcxUHZpU2svelEKLS0tIG9kOWU5Qk5DRFlKeHhLRTNqS2Qw
            ZmxFcjZ4QzNaQzFqZ0JqUm1FZHVNUE0KMLBzW8fKg7V/MYsBHGruwBOZAMQ5JYLz
            4oZ4fFUTxRr5OBcfgSV6gA3CuIif7vwk7Ghhgz3LxJeATDd6MVXusw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-09T04:56:42Z"
    mac: ENC[AES256_GCM,data:yYpu673UcTgm/y2zABSp/x/5E57IBWWeT1c6rWlpZjnqKi0a65cKRgbptEf2Pv5/C3Drm4Qht3nOtcgNrMlofUj9vMCaOTO8E7877ejjPJIaOi+DSgPl6TS2UUcSJmhTqFXrZPHdJi8cX2KWi75vbiri2T6Xh2QfVGNXdwEserY=,iv:mTjhXj2iATHjCVDOZL5+f/08X+WCN7ajifV4Rpfx/b8=,tag:p01zHQbai5AfGWlxCkGvDw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
