ansible_become_pass: ENC[AES256_GCM,data:ZYPXjto+sbhW,iv:YRilC/SIj9ERw69KyrwhzUOXmMTmOxOduGn/AUDHt+o=,tag:Fu2dSOflMqVJsCM78T7rEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x4aarl9ggry79j5n8uffmgnje7gnpjrcdz0aqp0kxlaaz5e42stsp0qj6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWjh2RlBjL3BRK01yRUsz
            UnpUcW1KOW9vbWhhTWRKcU5mMFdmWHJDSEJVCktya2RsMU13NzZzQlJib056dUNC
            UDVjLzU4MG9HV2dIREZlaGsxUHVJaEUKLS0tIHpSeWNvV28vVjRTQTFFWTBZWWk4
            WWNiNHNFY1FWZnVxUDdmTTZ1dzNXdVEKqvQ+O7FV107i6gZ4/DCj8XJVBLlIoDEx
            ml2HqHiRxSJzkML6kpNq9Umi7WtQXmmF70f08cIQ62tXM1g4h5uqvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-10T05:02:08Z"
    mac: ENC[AES256_GCM,data:M5IIFa4KbuwJyPYciULid64QcCnbo2AHlb5oBKaZ1jmBHMcQpB1y5hI2C5r/M3Laq1J56pA7Leyn2yU7n8SD1wxawIamFJr6i8yGvQy4m7mk7Ur8SIHNQY5w1SWtpxusL8rcpq8DRIBdxV6cFyxynuwVF3q4PdEwZYVsyJWPYYA=,iv:YfU7wjAVNYF4gJU0I7WmozkWRK1nBxrHzVVZ4N7IMMI=,tag:rsBvJnJtyvJCW29C5WL7RQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
