ansible_become_pass: ENC[AES256_GCM,data:oswJp+wLSMe9,iv:dUp7sJQ1vG1KvWrRiUzttwYS6ZZvw8yIzoKYU0EDPms=,tag:+Nctj448NzvSOO7ck+CUXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x4aarl9ggry79j5n8uffmgnje7gnpjrcdz0aqp0kxlaaz5e42stsp0qj6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIcitrYnhKZEpoMmhqKzVP
            UVBIbjJBUnJtajFKZTZzK2E2cVdTOTh6U2lRCm1zZjJxdURwdFkva2prK3ZyREti
            eWk1akNTaEQvZ240TnAyTTVlcU1lbWcKLS0tIGVFTVMzVitmMmhQMHNXQlZYUHhx
            LzRBOVJzK1JaVTJxTitpYVFGQWJwMEEKrU+wpFU1alPAy3Mzd7x50644eIfKpLkM
            nxIBGSxo2M1L4CupAqT1gW3ffjuwD3QajXA31n8UFcw6wMG1uUTSDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-09T05:13:59Z"
    mac: ENC[AES256_GCM,data:NHp0J3h52HVVgmmGokJi3zh352ftKjhfbzJ5mPXthT3jJI1Bza4cN1VKmLcRjLoLeztyDrIuDwOwBNP9fi77VEKo20+Ib3DyDr8QtbqcuLP4ZBu8L8ExvM9EfgxKjjq3BofzWPOX86IbGUpG8FPPhYfU0ELE/SnMNkaB/YbO6UU=,iv:z47nAq8NTK1wQGs9eW90K6g/gqL3zGCRdz6bAYTPbS4=,tag:jYFZBpi87AKMI0Sfg8EPRg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
