apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:61KiKPvJ+0ZCrbWyzC2ugEJshlY1Mosk8b4pxrwgQfXa2CE945QkcuW6SwwmJKI+Ol00e4cQy5GoehJ97PArPQ==,iv:mVzZCmo3HeGPANtrJZVHXhoZXVddEwkxIapzfJEGYDc=,tag:e/QvhxuuEKxvI2snqey35A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x4aarl9ggry79j5n8uffmgnje7gnpjrcdz0aqp0kxlaaz5e42stsp0qj6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBObHcvaCtKZDlJN1N2MnRl
            V1BUVjFwMFFTOFBIWTF6TFJHMitQaFVKd1ZrCkd2N3pDVzUxZDljYlR3bFA5RDJq
            cTMwNUc3SFNIQUx1RTVxRzl1b1EvZ2sKLS0tIGlTZGxNS0JtVGhqZDZhREtqQXNm
            ekRmWGdleE0wZkZsOVJCQ1JzMGFLMFEKxf05qVGtmOhi2HyTrK85ZKb8k/AIMKFK
            +XCTc+GvESiFcOjLBxt8f6QE9DZdP2wz0yY2T7h5qYUHrdknNdTU5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-10T05:02:50Z"
    mac: ENC[AES256_GCM,data:hH2qinfYXXvaQlAmiVKagxMY8rJBiJSL5ABidmFgckIumyhRLhIC+GMD5WY9qk1Gu6l5K8QdWIj9dbs39ydnRpj2RCns3Pw0r+vo32zAZZJv/mp6i+x9Q21jTq8mOXhzjaEW7zIk6ysi1PSUwsOAWvPT9GdYxh6qPLkC9tRokP8=,iv:/BeeC0hwXyymAsMrabc5eQCavnIgQVj9lNXCGC+9Kfk=,tag:6jK+1WtlrR5EawYUC5rCwA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
