apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x4aarl9ggry79j5n8uffmgnje7gnpjrcdz0aqp0kxlaaz5e42stsp0qj6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1b1BUQVB2WitjcW9xN0pB
            aiszV2RUMENwVFpDOHIzN1poRktoMHlSaVVZCjZzSkJ4QzJPRlFVbHRodlpZZzcw
            c2NGYXdFaFdRa1hKUElFbHEra1ZKTE0KLS0tIC9LSUNvVVI1VEhLei9pdU9OdVlW
            aFRXNFRrVjk2UHpqZ0JJOXUxallkQlEKJBdlfmn/9xejij9mqF98tRTMKbZ59buG
            HCsyJKPHxIxi47f5j4xusLL9tU1aXcoEXgdGsf0BAcpVVZr6/nyj2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-09T04:26:05Z"
    mac: ENC[AES256_GCM,data:DGKNwxyzA9QMQBE0t3T+bwCLET/a15DeKQOwlElIJ7S62nw+desR1yjK+YXjmTmCU6JmNmAtkZMDyIGm6tMKymU+BrBVLFvu1XnG3cp9EP+WysaEBHEPkigTZrFFj6nuzxDP5o3oHR3dSwYSIikcJ+gJOjfFKJa/QjDeBsImDoo=,iv:sTbrZJbtN6eeO5u6/Y/PJDrQfQvy8I5J1m9TZjr5MK8=,tag:vf9Q5VBmvg04RJCxksFrig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
