apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:HEPUOmzFiR5InNgH3bHEGMczyD2DOELqgv3mQvqyKQ6uZjSCaim693hvEHjqLGPumrEh2hrAX1Yc5ED7LezZQw==,iv:tdB5HlCAQy45f0opYl05Fx1p+7UNjuAzLXGs01X4uw4=,tag:qFJPJ8Tr6kk9FF8AhyRK9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x4aarl9ggry79j5n8uffmgnje7gnpjrcdz0aqp0kxlaaz5e42stsp0qj6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwV2RnMi9vRVVtbFA4TCtU
            NjZvZSs3Slh1S1R2bGMrZUZUNlA2dWFqUWdJCkFHWHdvWCtOLzZDL3RQNjlhQUtG
            T014dk9xaVR2WitQK21jelkzYXNlZEEKLS0tIFVOU0dWSHBaMEdPNVcwaE5RN25s
            TmdGWEd5TUgzQ2diNkwwS2FiT1ZWU2sKxWRA6/71BM/1pgXl4W9VT1VKTb1ocSqC
            TnJDh0BA8mkypdycHfYyFzfR1NnpqXtFhkSQreRejqe2/YG4PEGDQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-10T03:33:04Z"
    mac: ENC[AES256_GCM,data:QNywKsIEzJ/Zp0UKQAMMA9W0S/aj+mbAxd2nde9LahqBly4mvlXYg953EDSN6WfY3b75c0chw7x54HNuImwZN4caG7yHapwE8DBKEJCPltl9jOAsHMH3azt2r+0ge0PiSgBOSamgRvMeBYR67I+OTanDDVnK0z7vIkbFkrfNCiY=,iv:P/crSKKa46v5LZQ5B15FQ9Z9fS5+uKPtOfUPalvyI/0=,tag:cE09z0aodBfMHgQYenGE8Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
