# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:etYS3llSxgJa9TDEcUC7uSZubZW73BJ4jNAPvbLqch8=,iv:9sSrMyFYMAWMMScFvz1pkat8I3omShqkD5DXZYSTgQE=,tag:xHrY5i2wJKPMjQzJlxsNMA==,type:str]
sops:
  age:
    - recipient: age1y867m67ad9y7ces58pfkayxw8qce9ls6sk4z33hx6yvztjryrafs4n42ru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyemhiT1dhczdOckpRdXU0
        OSs1V0xJTmg3ZlE1VlBHcFhFNDZpbzBoWlRjCitEZC90MWpNYmc4UHBpd0EzUnp5
        N2MzYyt1dkRwVXFQQW1xeGxmSDhTQlUKLS0tIHJDckZqRURlaWRYWXZnNzZmd1Mv
        MExUQ0kxK0FDMzdlbnZxUm1WNmViNUEKJE+kUsGVbfNoy1RONGNWKeTg1oL8mosc
        ma/W0GJ0uXMwV5m8yHnw4Hxc8RCEh94wClyakXeYbHavAWCE5QfrGw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-05T21:11:46Z"
  mac: ENC[AES256_GCM,data:ZCS9pbzS0lNK/D6RobfhliWb8hzMa/1g7ouj39weWealsZ0Px9R8NIGnB4i5W1qSXTNpCFVSyMh04kaXF///47znPqZDcVo2ZIPAzh9BR4ep4iGUfskYKGR2h7iTPHo+NXv5RnVrGRWFCsZemYswlGXGjCqQkGEowmf/VEpTnzk=,iv:UN2T932oEnAr1VvtexGqJF/cahTgSsGE2fvW5JFDvcM=,tag:cKSOPXa+LL7KqBUZNFdibA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
