# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:pMx0s+nhrCjajGFH1cPCF2sG1vSdXRiICk/rfAYY7jE=,iv:TBsvGg/h3Q3UVxKemcGCI//bUTObT70nKNmzoimREXY=,tag:onTMWyM4DMVI1g/kl3BVjg==,type:str]
sops:
  age:
    - recipient: age1y867m67ad9y7ces58pfkayxw8qce9ls6sk4z33hx6yvztjryrafs4n42ru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpOXB6YVRwQ29BZVZ3Nmlv
        RU1rM3RoSzZOMkZ6NkxMS2Y0anlsbnliY2cwCkh0bkJvT1RLRWZhY3RQNXk1OU5z
        cnhBR25JRjgrcTBobkdqMWRYQlI4TjgKLS0tIDVEeXkrUWN5aGhmeEk2ZUVnbGhF
        MWxOb2hqanVRVjh4TlBGc3RqWVJzaWsK/TFV7s1lY+1IQPs1qrZ99Iew/EQxC1h6
        pV349hvor7Fidkv3u9ibhHt3B/s5TaSF9jU+FidDbBx4CG70iA/xwQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-06T19:51:35Z"
  mac: ENC[AES256_GCM,data:kDRdRc0wRltf96bI7Gr4j3bgpJaKazm65R8wI3zf2/4Jl25fubyF/JPMWzAvnB8gBqWpzVl2Y+kOQAhHpqXZiJqbsgA+0Tw239lGLmzV0n5/1Gj4PDyswreFWbB9PrWolX8o+ZQWTCLV/28HUNPXPQ88+tapTC1e9+PWubigXuc=,iv:u5gatnCWVd05BXuLl40DHULU0m0Nmzlhg1AmJjpJ6hs=,tag:TOTct96BR8Y3nY9lHeM+sg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
