apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:jBDTWO88cZCato4pknhYZcWxUlwe9vURZc7AH+tK7DuiRxreVbaR4w==,iv:eTxd3yLmJJF6USJsBxmbsfNCfTFoHZFbgjAwamCHYHA=,tag:6jJlzAAwLacll1TQe3axzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x4aarl9ggry79j5n8uffmgnje7gnpjrcdz0aqp0kxlaaz5e42stsp0qj6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5MHE3UWR4YUFBYkRubmVW
            K2hITUViVjdhdHBhcVlmTkIwd3ZlMkpiakFJCi93bHVUdzVyelZQUXJaOGpGWUJF
            N0F5d0g0dDZtR2FNVzVQbFdZeTBGOXMKLS0tIFBYVVZxSVlmQS9vOGE1REZSZFZO
            Vk9WK0t3aGloN3lMRlgvUmVsZlpqNDAKtTdYk/KOnxhGKBRbKGeQt2XeSvWaXUIN
            i6YhJv4Z74HMDAduOHHe2McF+0Gf8S1tY/tsg2/TIyPg5Rn8YJ71zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-09T04:26:05Z"
    mac: ENC[AES256_GCM,data:AbUhrKt0B3SI2iOLIkZLnuxtd57cTNEY8WRguILk8wdeeWV7Ti0PQsP05MrMBHNW37RNVyMvCQW5veEiQmkU1X0M/oMpQ+aFdN4aaW3Iw3lm4b7+4UU8hDf7ZDZWX/BxbWKz8cDzubO9Gx0rfR05CLAUWRzAPg1OO2nlIZsoBVg=,iv:Z1SfS8gwcksFBaRl5tp9vY4aTzaPNOKKnVpCcI6Cf+k=,tag:6AOJLk9IZSWiogRjPhVaew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
