apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:PT5AIbR6r9hZkqDiZpT1ujzrKJytJv4KQ4Sl4OcIw5ofPBpelwMR0g==,iv:tv851e2ikIwfGXJdNGLbuBSKM88PYs7l02aHyLFi+7Q=,tag:SLuqTtyv1Vxga7TGRP5wuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x4aarl9ggry79j5n8uffmgnje7gnpjrcdz0aqp0kxlaaz5e42stsp0qj6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Q2ltVnV1aVYzN290TytE
            WGFybEM2bWhyYmtWd3FQNktCL1ZrdjNldWdjClZ4SC9EVHI2K0pVSUlyVy92MTlx
            b1hnYWpDQ1k4K2pBWGVaNkVhQ3NiQ3cKLS0tIEE1T3BOdlVGOW9YU05SZ1pUd01m
            MitHNmUzNTJ3Q2h0aSsrK2hkSDg2UDAKvIr6O/8VqGrrSMYyOUPGTbYrMIbNDfi+
            qLFdpElXOPSbUF3YfBo0yQ/M2Qzta+kXWI+ZZGkYtL5wM3OtwmKMCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-09T05:14:39Z"
    mac: ENC[AES256_GCM,data:LYFK55KB34NQmiGhkf7ps+ak5gv7K2frZiLZHubBudWt6FlXLCzLDdaViDZHfqeEeFSUyPNd3W2QXieqiGEkkYw3sNDAs0UHXcXJeBhfSrcqeoetztU6/DvnLA+IGpRO3KmkDQfM/vvfStzyxIdGIIWVe5sAsj16+SITfi//k8c=,iv:8DiFiaki6zvIyIJfJ99VoRvycEmgluXefMuvC8LGLXk=,tag:idu26c3xpdcX4cHcci3aaQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
