apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:/hxSaNKyuNXBjXO1k0F/6q6VjJ/FtLL3KIKnC05TUYqEipXlUQLVKw==,iv:4vvHmbkdhjYJrHCrLGYdDP+30YFdlXALpqOH7IISOTc=,tag:Jr2PqPRMeOVQmW7ZAkWSpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x4aarl9ggry79j5n8uffmgnje7gnpjrcdz0aqp0kxlaaz5e42stsp0qj6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVm10cTJ3Rld2ZytZQ3J4
            UDYxd04rQ001eGJjeEd2c3FyWXFTZFMwU3lJCi9OU2JrSnJjKzNBN3EvVzdoUys2
            YVJ2RXY2OWthWk5wbFZuZzJ5YlVKWmMKLS0tIFVDT1Z0bmxzUm0rQjl4MkF0eXdu
            b0pIVjJERzJsUWl2Zk9aTHl3aGhsMTgKuK3d6pFgUG/YT1lpPxbQ5pRRw+2UTbiV
            jpiNTa18uwlaxo//JkkRA1YpJ7W8xLgtK2p0L5C4TtTrh4NZMJLa3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-09T04:57:23Z"
    mac: ENC[AES256_GCM,data:xGRIHL90WPikucOFCHF5xo2P0qzXzB9b8cg01EvaGmrPOzxbQGNimQ8cIsmBAfCznGMIRhYbp7nf1athCVLu2uzkIAFPtBR9V73aMgP/xt2WrtFVIx7Z7eBJ+kOfvrJeq/luA9nNVjltTLKQ/QQ+5eR/IYAQddy9YXxJbcUKG2g=,iv:oUwkzBfif/4RKA3N7Pem9rmh8GHQnnzOr4gZBe7p1n0=,tag:cHG8+0eGwMx76UwpQQvALA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
