apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:wZbL+e1a4yMUwaTnxuutnuBTfmFXVvFlsR5p+GP+7VYV9CBLoVdKqQ==,iv:LJ4huyJ8zSFoYok1ZOMGFADKg0Bs3DmC4hyjoeromR8=,tag:bBm+LeEdYF86bldWzXKUWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x4aarl9ggry79j5n8uffmgnje7gnpjrcdz0aqp0kxlaaz5e42stsp0qj6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVHM2Mi9kK0FHMFpSZHRC
            Zzd4WDViclNDek94WEVTU3d6ZmJsWTJVL3lRCkZ2TjR3YmdCZGJVU2hlV2pHcUEz
            dkN3RjdwQVA2bHpKRU83Rzd0N2cxSGMKLS0tIEpDcDl3bHFtL2N6aHVpTGxab0Rr
            S2srQ0RLNm9JRjF5UG8zY3Qra2ZXNzQKaucCwXCs50u2nPGx3/kjSqgkBRXg2hjR
            Jxaw/9/8mjPr6ixhATCq23bqRoC03NBfjCIAUUSJd1KLJ1Y7d5mF1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-09T04:26:06Z"
    mac: ENC[AES256_GCM,data:KI+elVVF4SJ7ALrGyztWj73NFDVQl3N6Y63AEzqJQR2KBuY/9NGq4+/I5WUltZEv3IbEaYPu9Y7a8zzrbE2NRn/TUc5kxlBZtAJXC878n2oh2blbjqR2KQVHlfko3Olom6aItFu1GyUKOX4rMYGR6tLOljuIEMw9zv4t5yz2MhU=,iv:G1Hl/qMfEAnJgxZPZH7v0sfFiNPQvYKCwSfrx68fysE=,tag:VvOszsUpELbm7y4Sq0Mtlg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
