apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:ia1VuMop1kzrorI7tjUR+pp8wnmq4v3vBVSrI3a0J67Q6SFPCxTi+Q==,iv:wRj1jABlMlI5pUPKXDvK021wUVj/prZa/JGaINZJLTM=,tag:z7M0BHPbpzGFiquRSABEFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x4aarl9ggry79j5n8uffmgnje7gnpjrcdz0aqp0kxlaaz5e42stsp0qj6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcFVySTBmYUJnekxGNGlR
            MGoyQmJjZko0S0p0ZHg0Z1M4Y0hVVnJGc1gwCkJvTmhubTFKSkRxb1FDMmg5Z1JR
            eVRQQXVYLzFYdkt1R0ZPK1prWUhYVFUKLS0tIDBQMFB4anROR04rOFh0NWZtU0Y0
            UlU4R09HOE5VSno0V2JnOHJlYnF5UkEKQ/tWAVbzzwZO2lz6T5wXK3AwWHFSj8c5
            RR+APBb2ru4uACdbRYFZ94gYaKx9QN8vrU2F8dNxnDGQ6/CG/xnLFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-10T03:33:04Z"
    mac: ENC[AES256_GCM,data:O1HIjNttdOeqGQ0aRPwq+Viglxx34k8efJhGa10obQjduSf8BkHnVariVqtSzU/YZi+Q83JVkcaTwPPlaiWY/LUiyBTvOCQ3x+1YJ5fOmam9CRrm3X8G1ImdHNDJkjTr65BE7RNhYASjMu02x7low/PB1bNOuqUhuSkHiKwAlXc=,iv:deoRPmoLAywIzSjOkhIynMQzVIIf9xCya6IGqIXwbMM=,tag:f0QW1MhXgkcIWKutYtDV9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
