apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:M1e8gH+6wTRlxMDULne9lmm+k2d3nJTFVKSuR56J9OZ7c4pkug2trA==,iv:NToaQM1GXEyF0y7//UrCbUcGb1db5sjmKW80OA4YJg8=,tag:WqTkU2eiEV8Pvsij6HYTCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x4aarl9ggry79j5n8uffmgnje7gnpjrcdz0aqp0kxlaaz5e42stsp0qj6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdCtsOEErRGpYYzZnR2Fj
            Q21yaEt0eXViOWVXVnV2TTZKZ3RqTGJoNGpjClJOemRMd3ZESndPb3NUbk54WlV2
            cXd6ODRuUUJBbmhNSmgweUFHWlI2dVUKLS0tIE14WDAyTUUrZDd5L3YvZHpxcVI2
            ejdzTnFJTVBxN2lBdm5aQk55dndSV3MKE1ECXfJhlZsjUMdX75tHsPWLeAlw161s
            X4pSqxEg+TZ0g+r91O59AeVttQZwfxSZsCUgIoeSHInHvxhpeAZ+qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-09T05:14:40Z"
    mac: ENC[AES256_GCM,data:aaUcG9dgWACmKTCo2FBWbs8HsTkidROL+icvA3F49Kh9DZFYlpR+FNNRIhXniVEKt9jhxh9CB9h4FzSRgpvHsxbx8sXW1yqnD5J3ydgEPORCOkYFZ5fJNikakMowLWvdDEavFMiw+ufjLAFUKoko/cbycUznMN2RW44qnx8G3fc=,iv:5u4WUdV3Kod+2pvWNTUT1B8efVLMh9EMDutEXsqc3J4=,tag:Jrr3rLViUJbyi7iww6Ar6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
