apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:SkMHWf2Xp2KmTvPnZwk=,iv:KUOhjDBFbDAd7inNcF4To4Uku5SbzhC/ukc+bhQzXx0=,tag:EIGv12wrevg9sxMa0eoQ5g==,type:str]
sops:
  age:
    - recipient: age1y867m67ad9y7ces58pfkayxw8qce9ls6sk4z33hx6yvztjryrafs4n42ru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlejdvTE1HeEJXN2VLL08v
        czZvVytHWHdKMEYzdjNkU2ZDdHZ2U3BMTmpnClJDeVlKYUhwUmF4QThjeFVDbDd1
        N3JqS1RJT0x5U3lzeDBtTW12enhQMzQKLS0tIDlOVnFXdExSTFdIRmxqWk8xZGp1
        R3VUVlRjN2JXZUdYQnRJYjJrK3pGdVUKhIu7vbpPDUM2KpcCuwbGqkMn6SbAhUFu
        15nc8yCwlc0/nJKFjq0jRnAo2qJf49ysvdSjt7jKTBuVrS6uUACqUg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-05T21:11:46Z"
  mac: ENC[AES256_GCM,data:WAeyVTGq33wiLcp96yaFoDdVEHT/9adeIsvsuHf4jLhKrREbMeJ6TibnZYBXT2sxpIwyVq1D+LOuWi29dKiS3iT7yrNNCX/eMUg1hftuc1mKuY0Uu+44mCb/RobnECP2oLFwJYE/R6tEHR3Eo6nuoPwRtAMU2QiUpscKY1TBv/U=,iv:oiw8MimxL7ozSgsUFXXgX3jhYRa4KbSmCn4pSH0vc/A=,tag:8GHZcc+Ogrc+C7nA4V9oxA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
