apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:zGJc5VBjRkp2yeVd+GIb+IluMoi4IHB12AG7GZln+PQ0JA8+iA7eKSB9jkwMUA64t3tat6G/mjPwOMd7WUkAXg9DNr6KaQhl/mk=,iv:Thbovlo5L29IwLsu3wHMwdbopBd7kpPNmLjWcsjQ6iE=,tag:iNu42MSuYg5PKCaCnG0QkA==,type:str]
sops:
  age:
    - recipient: age1y867m67ad9y7ces58pfkayxw8qce9ls6sk4z33hx6yvztjryrafs4n42ru
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTLy9kZUYyakowYzBETCt3
        enFLMGova3BxZnU4V3Rlemtjb2x4MEYydWdRCk4yckY1SU9IZGIra3lueVJ3d0Y4
        WkNOTXV1N3E0TzZCUXR0SFhCcTVXcFkKLS0tIHpKeVpLRmFFNjBycEI4VEJ6ZjFp
        U25DanBBUnRVemVyMElENWN6cTdVcEEKSmCoBYKXFBTs+CCeYW2kSbq51U6HFJLl
        Uw3bs7odaK5ambnA3xZLDbavi5n4dFuU6pCh2gn9DzIaSpmZKLO1Fg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-05T21:06:19Z"
  mac: ENC[AES256_GCM,data:ZJPde2/0xWhDy8wQlaayGXMsxTmy/sKngmQRGgqgK6GzaZD1YNcFlNS3U0Reo4W0E9shziPdH1MNznXYND3TB9+uhT5oBFaqo/1atlJACwyruJrTTP+MPRRae2OjLFV2aw18/BnyePCVWgPqWYSskMSvqJNBt4go2wU1S2hCbKM=,iv:ooF8lYrPF7Pa4Cs3355fZNTg6ce/jXH3ZhcVa9k0gZk=,tag:x31eMcbEExRrJMEeW64Yog==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
