# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.5.4:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.5.4"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "talos-cp-01"
    ipAddress: "192.168.5.105"
    installDiskSelector:
      serial: "vda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:db:db:63"
        dhcp: false
        addresses:
          - "192.168.5.105/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.5.1"
        mtu: 1500
        vip:
          ip: "192.168.5.4"
  - hostname: "talos-worker"
    ipAddress: "192.168.5.106"
    installDiskSelector:
      serial: "vda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:a4:40:67"
        dhcp: false
        addresses:
          - "192.168.5.106/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.5.1"
        mtu: 1500

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

