apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:KFR6NbT1WfLEnRv4,iv:IoWGnTvJhqA4LAMjAiZOqa90+GKFiPVY0oETPVm/ysY=,tag:kzl72EvLjx+h7EUV25Tjsw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x4aarl9ggry79j5n8uffmgnje7gnpjrcdz0aqp0kxlaaz5e42stsp0qj6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3aU9LZURJTDY5VDgrUmVq
            TWhOSlNsZkZYdHNiK1JVSC9yd1FnWDZoMlJBCnhKcWNGU1EvM1FVSUVHV3Z3QVcr
            N3A1TzhRNnVGNVU5a01sM0RUUDdRaEEKLS0tIE5hYnNnOGxvek14ZEg1a3VBdU9U
            ZmR3VjVkcHl0UE5rUEgxOUozM09IZVEKxVnyxM250+3TFtPC/AeDJf0On9NQqLQ5
            RcbWn7GnvHakhkTdl7Ln0vWpUot+Fo+NY0HaxYde08I32dVr9RTZzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-10T03:33:05Z"
    mac: ENC[AES256_GCM,data:NV+VPJZKTXrE2IsyBeKBooXcSHmsCkfunUy83BPiVrvoQvOFQehP+N7rrzXSv9h7S+pVrgGfcacCtGlTmigZrjaPtdGPLZC4vUzDRFMnIajaBT+tcDEAMBWVj4RDDTrdnqDhGzAI9F/aLkVXSW3Kl/OFaqOiIvOIVWYzDNsGJBI=,iv:0UFZnIFCF2pRpXC0ICbMx6z+JWYLpKp2WEhCmyhkoXQ=,tag:lP+HBsR5kTVTB+aQo2VQKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
