apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:wvGWO4hYHRF49LwJJQrduQc=,iv:KW+myU8qLh8XwYIFvUAUZYAip42BmsGVq/LSwA5WPJs=,tag:xCgAFR4NNfW0unhKPVUZlw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:ADaQHvDeVYZKTXmFiqGE2AzPsm7alx7emBYmo4RupOhj4Rov,iv:TmO512q/JOqz1UjG24oyCA8XymXQiCKD6Srg1SQjCAg=,tag:IPQq7OHKDkG5huIwLXs8uQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:JyGDvcEGPnOz6g==,iv:OLU807bpsdllPYJZi7XDHoWb8+3fPGK+svkCQpS8GQM=,tag:2E9IeeD2CqK7yRe1/yj2pQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x4aarl9ggry79j5n8uffmgnje7gnpjrcdz0aqp0kxlaaz5e42stsp0qj6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrc3BaZ3p0Rm42L0VGK3c1
            cmdMdFYxMUhSZzNvSWUyS2pWYVpjVzVmM3hZCkJjSGdyTWx0V2VIQTEyU1NUQVpK
            M29hQXZSRU1jTjBSZGh3Y2JWcXNFckEKLS0tIEdPNGJndVZDKzBpRHZQZDc4aXhx
            K2dqWGloTGV0WmptdHNYRHNTajJhYTQKn5Z+/xw/isLOj6wSIL6fcCC+G08F2Whi
            BFNbjPPY0UG0hkQP0uV6qnqolDP3lHsNVjb3wF4/8KZgcWKrm2wQgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-09T05:14:40Z"
    mac: ENC[AES256_GCM,data:9M/v4/m7iiHPTbP3kzMbN1JnqmeYrYO+lonH1zjD0JjM0zOnEGfnw8IxayCwgPlbVWf8roKMDOv8+2Ok/hhB++7XfSjf/mee0TlJKPV+WOnBziw/8pNcsmvmasSBf7JcNbM/T95O/E86DQHG8n8yan7ZLPht8WVI+KfZjS8h9ws=,iv:E7P/37n158pwfBVSUrX9BFKwr1zn+2ve+mkCNRsbaDc=,tag:vRE2Uw6kqBztxIV2qOzl1A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
