apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:L4saPXaxrtwFtahf,iv:BHreotV0qgIsyyczLDHgieYQcTha0FjwETKSrzD76Xo=,tag:qMLgYYc/h4NM9oa3DUtDQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x4aarl9ggry79j5n8uffmgnje7gnpjrcdz0aqp0kxlaaz5e42stsp0qj6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSkV5RzlrSFpOUytkVVZE
            ckc0dGtzZytsamlkenRCeXhoRDJ1SjBTS1NNClpFT2tIaEpvSThZQzNaZDFjbVVm
            VlFDVFIwbFdJVE9GRlpLRVlMTlgyb00KLS0tIE13bDVnTVlyQlhDSWRTd1pWTnJQ
            NHZ4SXpkaTY1OG5SWTdRN2JBNS9CTVEKW5JePZ+MhfzfBp9HdO9CVk2pwYcw3rsO
            tsAKraXF9YisdEs6ULgzcqIC7GWCBVhqpdHUJYwA/SyalJlWKlrlfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-09T04:57:24Z"
    mac: ENC[AES256_GCM,data:Ob0G06/ewRFNTjsgbhi3K7jqPm5E+IgrTk/naqnyb3MyObz2d94NBHCOMTcWsi5UYTvE2wJG6OC1tarUTpoU4mobM8xNLWTKR6d5tY48b5/4v4orN8Xm3LGdJSVtJ+MqUw/lWxRjGh4DhfsHfdPMG39VTDt/kzATYbUfBJdVzmY=,iv:S8UOvROvPiUX6mtTfxe0ukJu0I85Xg/h8fz/abCRsjg=,tag:cvzR27EYVjmJssi1Cgom+A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
