apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:sU/Yns+N2ls7JGpA,iv:evADQ59B3ZdkTlSBpAsFgnF5pbPCvTTcTLQPFFXb7cA=,tag:fUj4CCt4rFZWpRBf83yBUw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x4aarl9ggry79j5n8uffmgnje7gnpjrcdz0aqp0kxlaaz5e42stsp0qj6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvMEJGbEFWek5yTXl5RXV6
            OVhTa2N2SEdEVFFRdDJFajQwTXEwbGlZbzJJCnVKRWF5VzEzNG9OVEhaa21GWFlC
            QUtXUXkyMDgvTEczUytUTU5FU0hRMTQKLS0tIGxUL2Uzd0tRaTRPSFFGTmdEK1pk
            cFl4WGVNYm9HV3FpaEpKRGg5aGxyTGsKav7Gu8IMB9EsjMyy1L0SpvXb/y0AoSgU
            PiF4eSYqrCR91ZR+g2zguenk6EaDV9XAJ6hjFgFzUVF1C6WFFU/uxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-10T05:02:51Z"
    mac: ENC[AES256_GCM,data:TSjQ7pOoMlSDR86Ntjgw2OhTtXYw670ypWFef9LNeBIXjtT5A+GCqs5FjeDvPgjZOaJxmO14wMbM9+TriWU8xOwtU2XrOglTFxUkUtWZYxktnkhONauID3hhgubZ6gFiXGN75EE3dLlmYF28il+w2HkYhUb+QlKTtFRQZkh+Tto=,iv:XlZ8TwpGj5Igr1bC21dbCT9W1eLFNCqRs+V1iJl1Vww=,tag:zjzS5baIsjxpXU6QvQ7qlg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
