apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:/ntux7lNBECEkZj2pOxP6sc=,iv:X0t3A0Ij2fXgUnP7FaknAavgKa22dHcAuBItwwSqbCo=,tag:LFuakqoAn9866VleyvX6bg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:neM2jfb2ff0F9WNL6XbqvasqViwmO5PSIy1VcPaRepbDslZv,iv:IA3fsNZkT9K/2zkS0V33Do4vKDkwEII7oWyZYzIiO1Q=,tag:h8HifipXQoPEJ9b8KrYUFw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:Mn4z3QZIBC3vSQ==,iv:EfuvKaES4/N0wUUkDyVum2nhQwU0aS7v+At+2HSavMs=,tag:NMoUwmIFe89pjX/wKtgLWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x4aarl9ggry79j5n8uffmgnje7gnpjrcdz0aqp0kxlaaz5e42stsp0qj6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZ0htUTFCOHpmb2V4UEtt
            VnV6bG5ob2d2TWR6aEVPNDM0eHRBeGw2VkVZCk95N2ZtMkxvcERnTkpXdVVvTENV
            a3BkN3FKNHl3WStLQlZocXVBcTc2TFUKLS0tIGRVZ2QzcmhmYnJmMmJaZ1c3NTdZ
            REdKQU9xNmpMa01QNHlHbUs1MDkzU0kKxmj1f58E3owse1q8q65NkmjvpFgzo3zj
            YXH6sWK2s6y4DochXCK9bRIWa0uqBu8HqqIvkaF0HPQCG64wYH78Mg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-10T03:33:05Z"
    mac: ENC[AES256_GCM,data:0ljTIzU2894s+xYjy8KxYMLBSI5uh985GNdmnuUSx4cvFsc4bkkb0DzHQ4lVrJlf9ABsT/wezVSKH6eGeW07Lih4Y7OqAK7fpSYqUKjsJhJbYLR5XeOsLj1nPQ4q5EFRHgJKDYjTe+Vlp1Y1uCWo5riu06TWYUqAfY6qFvTveEg=,iv:ahz+XI912eLsaVtkCC9i8C4UXG5xArl6ShTxD2St9ME=,tag:QCz7hExQe1An3gyIVzunxA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
