apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:UjoTq4UrKBK0gWYonBo0kEU=,iv:jzqvkyLpGKMT/tJy2vHkKzVTpinGYw3XPG72K7d7V/Y=,tag:8/GH+NuTV349AS9xUlseqg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:zPgpChLGnHLdxhdio5aN9iPM3dmTS6x8/TRKelfvAAYBgfM9,iv:b8KUPh7hkAwQ27BndaFEvTgqzcI76XjPsVtjlvQFRHo=,tag:Nsg8nuHFGGdAEYgFSqn/TQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:KFPuEloZzPCp6Q==,iv:DKSdqJqcK7MmoJ04Gkg+oZkbXr7yldFzYCq/h1Ii0L0=,tag:H4Ayt5mnNNu0uJ1S1dzFTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x4aarl9ggry79j5n8uffmgnje7gnpjrcdz0aqp0kxlaaz5e42stsp0qj6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSE1PaUhJTVRKTFJuSkN3
            ZTMyNXhmdXFta01xMUZZazRSbEQ4SW1RM1FnCms2YUx2WVFlK214SnA0UjBnblU2
            R08rTnNFd2Q0Wm8rU2wwMjA1WWVyNzQKLS0tIGxMaXV2aWcxWGtDSjM2WklHa3I4
            ZGZQbHBWM2ZTT2VlUWFFdnk1ZnpZTDAK0PDx04nb71O6wvooZpsWf+oObnYvRh7K
            HJ78xAYnEXpfyxvh4mmxlLPm+ZfiUmMIJ4o3nlbCih3Iz1vzJCfdAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-09T04:26:07Z"
    mac: ENC[AES256_GCM,data:yG5pmk0SsoaureAu4y3SfQrrCdg9FeniJo2AS9PlKuBmr8PbIWWnIogWc4ZgWPXacRX4BQI7bQ/f03UOlodDpWejYFJmOfJmC7SNwx5GZcWWBdg/3za+c9lltnn3CdpogPqZT/irUVJ/DRMgyIvUIYFHoOYnL8Knf8ptGb2L2/8=,iv:Cr+7kL6bAPYn9jWatWhURl/PuWOS1+9dqHrznMq1pnM=,tag:/ghn4DgOA4vHeSmGuP3FuQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
