apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:/7dCqTkn/KDuTJoHGucxbIY20XoFjz768srI/AahLMRGvNWX,iv:pxX1nFKeOS08gybl1BoJgWeKcIayQ09+pDEmJm7omd0=,tag:odNY4b0KF6X/vpgyRae9KA==,type:str]
    credentials.json: ENC[AES256_GCM,data:Y6QNKgtw5Z/H9Qun8Fz7sEW+XtpDQO6AJEw1hGvtMljLJIWzHC+8dq4UCgI4nXnmPBaC3m+D22CK5OmVX7qcniz05Z/KPO1xAfMN1dexh42H4sJB/870tLpSCoOD08vwehLf4nKv1KTI73WyVPGERKGfnTtltSmb1sG8u83sKo2sBVO5hn0UzX5yaDvqMbotYjB2zRklxtrtfOqi5CvYx9Y5M2MNN8LzsHxeapTmmw==,iv:t7LjBIvdMyihxiSdDNJZWtAMJtScZH/tsDLvd3et7tI=,tag:0vnwsFY7bNRmBSbRUKN0UA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x4aarl9ggry79j5n8uffmgnje7gnpjrcdz0aqp0kxlaaz5e42stsp0qj6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVUhCZGNnWGVma0oxeXpD
            YVpBMldSNllkdkhzdFVuYVFQajdSQzdjUEJJCnBkbHFTV1k5SGdvZE9YTDBieTNl
            NTQ3YWtYSWFIR3MxT3RpdWJCK2MzSk0KLS0tIGc0WWhiQ0lRc0ZRTldWT1Z3bDlK
            Q2hlWjNQZHhuWW9qeXBYZWxYK1BhWEEK6KTGrKRI9p0AYkzs1JMs1JItFxIOgaGF
            qeSPwu/b5gDmCWzGbWMi5W7dqGoWvG4WejfCe5N0Lp3G6+UpkcEa4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-10T05:00:11Z"
    mac: ENC[AES256_GCM,data:MSj7IYc/bMg8CPHdC+WrEcQBK2dnBATECPFiWr0tVkK0UeR2QxyMa82VOp3z3+IL9+/BFMqj7xLzYj5YGtBW+AFut44+F2HJ4Cp4rYuSL2ZDso5JR4hL9buyb6iF/OOMrG9w1lkBfmfg34R3RwAnb4q2KkOl6UO745LqaJXOVhw=,iv:V6djuNGovl0T8EUYA6YppT045zf8nrn53jb2ZwiFxXs=,tag:BG/c/FmejbbpmRxo0RBcnA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
