apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:sgBaaX+jZlxmuII/1O5tF7cdmNlVLoMgDTXgfkHEf1vyr+dF,iv:eUGWtrOBIkZOlvai6V5HO5kaCc4ZrXROy++rEYZpols=,tag:8ih24xxnkl9yjnMFGcnEwg==,type:str]
    credentials.json: ENC[AES256_GCM,data:+h1pqTIFOKYG38joO1EmrOFHEc9W9rr1x3LvgMTa/tpoF9CDl+teYuOFattPTKn4AT0q7qDniDjZR4o4DKve/OdcpMIDO8W1qqlT/JbDpFZwQFZWro024J5dfbhEAdQyPuZSM082lUVAj1aQCkhCgbrbBUK+diQbOAgTNhruteqeDkEN5QuRZ8fOnYDCtCjNgRBhw9LjLuAoeHaTb1RCkkBi6sVAaXuxmajdx/KnPQ==,iv:c/l/T2n5QKfwjd/KibGxKrOmTKa86meGrnJufPbcET8=,tag:opzSsRMd7+FYzEGy3OOsig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x4aarl9ggry79j5n8uffmgnje7gnpjrcdz0aqp0kxlaaz5e42stsp0qj6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0djdKbzU3T2swN1VHeDd1
            U1BkMzZJUElCWXZuVmpPS0JYeWJnVitYY1FzCmZYb0lQaWRIVzNUdjh3OVAyVEdQ
            alNMREVUWU1wU29nQmNQM3BhM3ovaWsKLS0tIElLSUdzQmI1TjZUUHpYRyt0YnFi
            U0QvMGZtYkZYVzdmV3g0NUR5MWR3OG8KooW581Ls35yGFU2cn5BUASPpyRQ5vsQL
            1PYHSuM5/U+QhHp9rHq7Bg8U/49XN4TEROe47XKbBsOe5YRJFKUvNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-09T04:26:06Z"
    mac: ENC[AES256_GCM,data:EEnzreI3QP8jhTQZCpZv4w9seJOe4xs9+leOb/0Oa01ddJu4OImM/HxfbE89uM2mrS8OzfnppD0LWT50BHfMHalwmW638dCy4S6SR0fCkb+ssgxgiY4EGYNCU4UkgY+rKuPZhsNdxC0YCZwacwHRXQAy4RBoZ/4tYWoK263OcEk=,iv:pfWNdFEysEvLUVERGhRgR0cY62oDLRLb/0HiPqpQ9z4=,tag:6slKXjDqN9Y0nL8KHs/Q0w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
