apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:YaBM610TkXF8/RhMz1UrzRll5R4I2ba8sHQ3XhBCwUlTrL9c,iv:TjeaiOP9uO+ofMAO3EOJQ5frwT9c4NRpGMO7gXUh52A=,tag:c8gRk8SJFotkgGX/Y/nK9Q==,type:str]
    credentials.json: ENC[AES256_GCM,data:f00lvjuNFO/y5CGPwd1LzKJVZfWg/lx0xW96/hCKlL0FTZPbgeCDP7NFcYbAAJftn+RMC8TuenR2aLcibosv8v/VOL+Ubjs9Eq9BLQlvZlZp1xCWaDZF5iL0ZV6L5GLHYxrMcx4nEl+sQPIha782NjMW2xtJu4VEA22lPBW3yOmRxNJyZRTDKlObQHq+M2C42Nge4GgGtizHgrFJ6vZfwPGIl2+rXxSBcs0QCQ3nww==,iv:vZ8Lte9DKU9L+7x9CeNkESBQl40M3qBBewRBitxlWfk=,tag:q+9gYfCeM6bZF7b+8pw65Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x4aarl9ggry79j5n8uffmgnje7gnpjrcdz0aqp0kxlaaz5e42stsp0qj6w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAycHhMVlNrdmZTbXk4K0Vw
            WVZHZUppTVdRRkR5TFp0Y3VJbFZmdG1ERURJCjZWY2ZBZjJjMGRWTWIyUlpRbGxS
            NEpWRkNRNzFqQkVETktyRjczS3MxT1kKLS0tIFppRjlwT0tUWmE2bWM3bXVNTG9k
            VmYwNzFoTUUybDlTemQwNEcvN2FZSmMKKeh7P+1Cn9jEJvHUfQokXJI7Nch9nVxE
            NUcUEn0NACxz/XxM1odC1kxeL1AcMXIft0j/S6G/rOFH9Fk3vl1QSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-09T04:57:24Z"
    mac: ENC[AES256_GCM,data:oRF6wqbp7G7tDp8jE/ECkxHjxB/ViWl+1Q6ycHTdlQ+FvUZ299+QpIkoFp8CntixjhCqxcRwtRkTmxP9KweCi98cbZRz0BU1j/1/aqBf4dfziBnqmg2LYixx9Opf8N4x2HuAKR8NRCJ5Hlw3y7v+O+wv2Nhg2Yyz4B6cpo7POyc=,iv:cUhYLfPqEm2Qh/J2zRHkFQojPT6C3ONHjy4U8TLC5ks=,tag:RZ07cXZqkgHRv5u3b5MjQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
